### PR TITLE
[Proposal] Screenshots

### PR DESCRIPTION
**Pull request by Ilithy**
- _(first drafts)_ Added screenshots of the application.
- Added links in the readme to the screenshots
- Fixed the "get it on Github" badge
- Added IzzyOnDroid link and badge
- Many thanks from me for this new app, which has perfectly found its place on my pixel, and which already works very well ❤️

### CODE REVIEW

**Comment by Bnyro** [comment]
Thank you, highly appreciated <3
However, the GitHub link seems to use a F-Droid logo instead of the Github badge :)

**Comment by Bnyro** [comment]
cc @IzzySoft
Thanks to @Ilithy we got screenshots now, would be great if you could include them into your repo as well now :)
Thank you!

**Comment by IzzySoft** [comment]
Updated the config and manually triggered an update – thanks! Would be better if they came without that framing (apart of transparency getting lost when converting to JPG, it wastes useful screen estate on small screens – and yes, I convert to JPG as it reduces size by 50%+ which is good for low-end devices and small data plans, plus for faster page loads :wink:)

**Comment by Bnyro** [comment]
> Updated the config and manually triggered an update – thanks!
>
Great, thank you for fetching them <3
> Would be better if they came without that framing (apart of transparency getting lost when converting to JPG, it wastes useful screen estate on small screens – and yes, I convert to JPG as it reduces size by 50%+ which is good for low-end devices and small data plans, plus for faster page loads :wink:)
>
Fair, we'll use JPGs without the framing next time to impress with great screenshots :)

**Comment by IzzySoft** [comment]
Wonderful, thanks!

**Comment by IzzySoft** [comment]
No prob, @Ilithy – one cannot be aware of everything. I usually try to keep screenshots as light as possible (they should give an impression of the app, they're not a "high-res image gallery" :see_no_evil:). So I resize to 350:x (portrait) and hope they get below 30k each (on average), which in most cases involves converting them to JPG. Which also means: no prob if yours are at "full HD", my updater takes care for that.

> Should I remove the transparent background too?

Makes sense, as converting to JPG makes it greenish; if you remove the frames anyway, it would be gone anyway, right? And yes, "basic captures" would be great! As pointed out, users whould get an impression of what to expect. You can still have a high-res image gallery elsewhere. If e.g. you have a nice Wiki page (Github offers that feature, so do Codeberg and GitLab should you move one day), I could configure that as "app website" to point users there.

That all are just suggestions, I of course take what's there. Just for best results… well, you get the idea :wink:

**Pull request merged**
